# Generated by Django 3.2.4 on 2021-08-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210824_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_id',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
